scan: 'scan'
base_frame: 'openni_camera'
map_frame: 'map'
odom_frame: 'odom'
iterations: 6
linearUpdate: 0.55
angularUpdate: 0.25
temporalUpdate: -1.0
resampleThreshold: 0.10
particles: 70
stt: .0015
str: .012
srt: .012
srr: .007
maxUrange: 9
maxRange: 10.9
kernelSize: 1
max_update_interval: 60.0
delta: 0.05
lstep: 0.1
astep: 0.1
