scan: 'scan'
base_frame: 'openni_camera'
map_frame: 'map'
odom_frame: 'odom'
iterations: 6
linearUpdate: 0.25
angularUpdate: 0.15
temporalUpdate: -1.0
resampleThreshold: 0.70
particles: 110
stt: .0000000015
str: .0015
srt: .0015
srr: .0004444
maxUrange: 9
maxRange: 10.9
kernelSize: 1
max_update_interval: 60.0
delta: 0.05
lstep: 0.1
astep: 0.1
